//
//  WidgetTheme.swift
//  URnetwork
//
//  The app's palette, restated for the widget target (and used by the app's
//  own previews of the widgets, so they render exactly as the widgets do). The app resolves these
//  from its asset catalog (Color.urGreen etc., synthesized by Xcode); the
//  widget target does not include that catalog, and the handful of colors it
//  needs are cheaper as constants than as a second catalog to keep in sync.
//  Values match network/Assets.xcassets and Shared/Theme/ThemeManager.swift.
//

import SwiftUI

enum WidgetTheme {

    // MARK: Symbols (widgets/Assets.xcassets, generated by gen_connector_symbols.py)

    /// The UR connector mark, filled: the tunnel is up.
    static let connectorSymbolFill = "ur.symbols.connector.fill"
    /// The UR connector mark, outlined: the tunnel is down.
    static let connectorSymbol = "ur.symbols.connector"

    // MARK: Colors

    static let urBlack = Color(hex: 0x101010)
    static let urWhite = Color(hex: 0xF8F8F8)
    static let urGreen = Color(hex: 0x87FB67)
    static let urCoral = Color(hex: 0xFF6C58)
    static let urPink = Color(hex: 0xED8FFF)
    static let urElectricBlue = Color(hex: 0x0039DE)
    static let urLightBlue = Color(hex: 0xD6E6F4)

    /// The quick connect tint: the control's and the widget button's solid
    /// white connector turns this color when the tunnel is up (the app's
    /// accent pink).
    static let tint = urPink

    /// The connect screen's connected color: the mark next to the location
    /// in the widget turns this when the tunnel is up.
    static let connected = urGreen

    static let background = urBlack
    static let card = Color(white: 0.11)
    static let text = urWhite
    static let textMuted = Color(white: 0.6)
    static let textFaint = Color(white: 0.35)
    static let axis = Color.white.opacity(0.12)

    /// Usage bar segments, as the app's UsageBar draws them.
    static let balanceUsed = urElectricBlue
    static let balancePending = urCoral
    static let balanceAvailable = textFaint

    /// Chart series colors, as the app's TransferChart draws them on every
    /// route: bytes in green, packets in pink (the client and provider charts
    /// use the same pair, as on Android).
    static let byteSeries = urGreen
    static let packetSeries = urPink

    /// Contract stacks, as the app's contract details view draws them:
    /// send in green, receive in pink.
    static let sendStack = urGreen
    static let receiveStack = urPink

    /// The globe's neutral for providers whose country is unknown.
    static let unknownCountry = Color(hex: 0x0099FF)

    // MARK: Fonts

    static let title = Font.system(size: 13, weight: .semibold)
    static let body = Font.system(size: 12)
    static let caption = Font.system(size: 10, weight: .medium)
    static let label = Font.system(size: 10, weight: .medium).monospacedDigit()
}

/// The mark next to the location name in the dashboard: a filled disc in the
/// location's country color, the same color the in-app location list gives
/// that country. A location the palette has no color for (best available,
/// no country code) gets the palette's unknown-country blue; when there is
/// no location to show (off, not configured) the disc turns faint so the
/// title keeps its place.
struct LocationColorDot: View {
    var location: WidgetLocationSnapshot?
    var size: CGFloat = 22

    var body: some View {
        Circle()
            .fill(color)
            .frame(width: size, height: size)
    }

    private var color: Color {
        guard let location else {
            return WidgetTheme.textFaint
        }
        return Color(hexString: location.colorHex)
    }
}

extension Color {

    /// `0xRRGGBB`.
    init(hex: UInt32, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }

    /// Six hex digits with or without a leading `#`, as the SDK palette
    /// returns them. Unparseable input falls back to `fallback`.
    init(hexString: String, fallback: Color = WidgetTheme.unknownCountry) {
        var digits = Substring(hexString)
        if digits.hasPrefix("#") {
            digits = digits.dropFirst()
        }
        guard digits.count == 6, let value = UInt32(digits, radix: 16) else {
            self = fallback
            return
        }
        self.init(hex: value)
    }
}
